Controllers/DocumentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataRepository.Models;

namespace bw01.Controllers
{
    public class DocumentController : Controller
    {
        // GET: Regatta
        [AllowAnonymous]
        public ActionResult Index(int? RegattaID, string DocumentType)
        {

            DocumentViewModel dvm = new DocumentViewModel()
            {
                RegattaID = (RegattaID.HasValue) ?  Convert.ToInt32(RegattaID):0,
                DocumentType = (DocumentType == null) ?  "all": DocumentType
            };
            dvm.HandleRequest();

            return View(dvm);
        }
        [AllowAnonymous]
        public ActionResult show(int? RegattaID, string DocumentType)
        {

            DocumentViewModel dvm = new DocumentViewModel()
            {
                RegattaID = (RegattaID.HasValue) ? Convert.ToInt32(RegattaID) : 0,
                DocumentType = "log"
            };
            dvm.HandleRequest();

            return View(dvm);
        }


        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Index(DocumentViewModel dvm)
        {
            dvm.IsValid = ModelState.IsValid;
            dvm.Entity.DocumentText = dvm.DocumentText;
            dvm.Entity.DocumentType = dvm.DocumentType;
            dvm.Entity.DocumentAuthor = User.Identity.Name ?? "Guest";
            dvm.Entity.DocumentDateTime = DateTime.Now;

            dvm.SearchEntity.DocumentType = dvm.DocumentType;

            dvm.HandleRequest();

            if (dvm.IsValid)
            {
                ModelState.Clear();
            }
            else
            {
                foreach (KeyValuePair<string, string> item in dvm.ValidationErrors)
                {
                    ModelState.AddModelError(item.Key, item.Value);
                }

            }

            return View(dvm);
        }

    }
}

Controllers/ImageController.cs
using DataRepository;
using DataRepository.Models;
using ImageStorage;
using System.Collections.Generic;
using System.Web.Mvc;

namespace bw01.Controllers
{

    public class ImageController : Controller
    {

        private readonly IImageService _imageService = new ImageService();
        private ImageViewModel imv = new ImageViewModel();
        // GET: Image

        [AllowAnonymous]
        public ActionResult Index(int? RegattaID)
        {

            imv.searchRegattaID = RegattaID ?? 0;
            imv.HandleRequest();
            imv.imageToUpload.Status = false;

            return View(imv);
        }
        [AllowAnonymous]
        public ActionResult show(int? RegattaID)
        {

            imv.searchRegattaID = RegattaID ?? 0;
            imv.HandleRequest();
            imv.imageToUpload.Status = false;

            return View(imv);
        }


        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Index(FormCollection formCollection, ImageViewModel iVm)
        {

            iVm.IsValid = ModelState.IsValid;
            if (Request != null)
            {
                iVm.file = Request.Files["file"];
            }

            iVm.HandleRequest();

            if (iVm.IsValid)
            {
                ModelState.Clear();
            }
            else
            {
                foreach (KeyValuePair<string, string> item in iVm.ValidationErrors)
                {
                    ModelState.AddModelError(item.Key, item.Value);
                }

            }

            return View(iVm);


        }



    }

}

Controllers/RegattaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataRepository.Models;

namespace bw01.Controllers
{
    public class RegattaController : Controller
    {
        // GET: Regatta
        [AllowAnonymous]
        public ActionResult Index()
        {
            RegattaViewModel rvm = new RegattaViewModel();
             rvm.HandleRequest();
            
            return View(rvm);
        }
        [AllowAnonymous]
        public ActionResult show()
        {
            RegattaViewModel rvm = new RegattaViewModel();
            rvm.HandleRequest();

            return View(rvm);
        }


        [AllowAnonymous]
        public ActionResult Display(int RegattaID, string RegattaName)
        {
            RegattaDisplayViewModel rvm = new RegattaDisplayViewModel();
            rvm.regatta = new DataRepository.Regatta {Id=RegattaID};
            rvm.HandleRequest();
            ViewBag.Title = RegattaName;

            return View(rvm);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Index(RegattaViewModel rvm)
        {
            rvm.IsValid = ModelState.IsValid;
            rvm.HandleRequest();

            if (rvm.IsValid)
            {
                ModelState.Clear();
            }
            else
            {
                foreach (KeyValuePair<string,string>  item in rvm.ValidationErrors)
                {
                    ModelState.AddModelError(item.Key, item.Value);
                }

            }

            return View(rvm);
        }

    }
}

Controllers/RegattaCrewController.cs
using DataRepository.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataRepository;



namespace bw01.Controllers
{
    public class RegattaCrewController : Controller
    {
        // GET: RegattaCrew
        [Authorize(Roles = "Admin")]
        public ActionResult Index(int RegattaID, string RegattaName)
        {
            RegattaCrewViewModel rcm = new RegattaCrewViewModel();
            rcm.regatta.Id = RegattaID;
            rcm.regatta.RegattaName = RegattaName;
            rcm.LoadData();
            return View(rcm);
        }


        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Index(RegattaCrewViewModel model)
        {
            RegattaCrewManager rcm = new RegattaCrewManager();
            List<CrewMemberSelect> crew = model.AllCrew;

            foreach (CrewMemberSelect crewMember in crew)
            {
                rcm.UpdateCrewList(crewMember, model.regatta);
            }
            return RedirectToAction("Index","regatta");

        }


    }
}

Views/Regatta/Display.cshtml
@model DataRepository.Models.RegattaDisplayViewModel



<div class="table-responsive">
    <table class="table table-condensed table-bordered table-striped table-hover">
        <thead>
            <tr>
                <th>Regatta</th>
                <th>Year</th>
                <th>Date</th>
                <th>Result</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Model.regatta.RegattaName                   </td>
                <td>@Model.regatta.RegattaYear</td>
                <td>@Model.regatta.StartDate.Value.ToString("dd MMM yyyy")</td>
                <td>@Model.regatta.Result</td>
            </tr>
        </tbody>
    </table>
</div>

<div class="row">
    @foreach (var item in Model.stories)
    {
        <article>
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="panel-title">
                        <h4>@item.Heading</h4>
                    </div>
                </div>
                <div class="panel-body">
                    @Html.Raw(item.DocumentText)
                </div>
            </div>
        </article>
    }

</div>

<div class="row">

    @foreach (var item in Model.photos)
    {

        string imageBase64 = Convert.ToBase64String(item.ThumbNailSmall);
        string imageSrc = string.Format("data:image/gif;base64,{0}", imageBase64);

        <div class="col-lg-3 col-md-4 col-xs-6 thumb">

            <a class="thumbnail" href="@item.ImageURL">
                <img class="img-responsive myThumbnail" src="@imageSrc" style="height: auto;" alt="@item.Caption">



            </a>
            <div class="desc">
                <div class="desc_content">@item.Caption</div>
            </div>
        </div>
    }
</div>

Views/Regatta/Index.cshtml
@model DataRepository.Models.RegattaViewModel

@{
    ViewBag.Title = "Regattas";
}


@using (Html.BeginForm())
{
    <!-- Start Hidden form -->
    @Html.HiddenFor(m => m.EventCommand)
    @Html.HiddenFor(m => m.EventArgument)
    @Html.HiddenFor(m => m.Mode)
    <!-- End Hidden form-->



    <!-- Start Search Area -->
    if (Model.IsSearchVisible)
    {
        <div class="panel panel-primary">
            <div class="panel-heading">


                <div class="panel-title"></div>
            </div>
            <div class="panel-body">
                <div class="form-group">
                    @Html.LabelFor(m => m.SearchEntity.RegattaName, "Regatta")
                    @Html.TextBoxFor(m => m.SearchEntity.RegattaName, new { @class = "form-control" })
                </div>

            </div>
            <div class="panel-footer">
                <button id="btnSearch" class="btn btn-sm btn-primary" data-pdsa-action="search">
                    <i class="glyphicon glyphicon-search"></i>&nbsp;Search
                </button>
                <button id="btnReset" class="btn btn-sm btn-primary" data-pdsa-action="resetsearch">
                    <i class="glyphicon glyphicon-share-alt"></i>&nbsp; Reset
                </button>
                <button id="btnAdd" class="btn btn-sm btn-primary" data-pdsa-action="add">
                    <i class="glyphicon glyphicon-plus-sign"></i>&nbsp; Add
                </button>
            </div>

        </div>
    }
    <!-- End Search Area-->

     <!-- Start List Area  -->
    if (Model.IsListAreaVisible)
    {
        <div class="table-responsive">
            <table class="table table-condensed table-bordered table-striped table-hover">
                <thead>
                    <tr>
                        <th class="pdsa-action-button-column">Edit</th>
                        <th>Regatta</th>
                        <th align="right">Action</th>
                        <th>Year</th>
                        <th>Date</th>
                        <th>Result</th>
                        <th class="pdsa-action-button-column">Delete</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.regattas)
                    {
                        <tr>
                            <td class="pdsa-action-button-column"><a href="#" data-pdsa-action="edit" data-pdsa-val="@item.Id" class="btn btn-sm btn-default"><i class="glyphicon glyphicon-edit"></i></a></td>
                            <td>
                                @Html.ActionLink(@item.RegattaName, "Display", "Regatta", new { RegattaID = item.Id, RegattaName = item.RegattaName }, null)
                               </td>
                            <td align="right">
                                <a href="@Url.Action("Index", "RegattaCrew",new { RegattaID = item.Id, RegattaName = item.RegattaName }, null)" class="btn btn-sm btn-default" alt="Crw List"><i class="glyphicon glyphicon-user"></i></a>
                                <a href="@Url.Action("Index", "Image",new { RegattaID = item.Id })" class="btn btn-sm btn-default" alt="Photos of this regatta"><i class="glyphicon glyphicon-camera"></i></a>
                                <a href="@Url.Action("Index", "Document",new { RegattaID = item.Id, DocumentType="log" })" class="btn btn-sm btn-default" alt="Documents"><i class="glyphicon glyphicon-book"></i></a>
                                <a href="@Url.Action("Index", "Document",new { RegattaID = item.Id, DocumentType="shop" })" class="btn btn-sm btn-default" alt="Documents"><i class="glyphicon glyphicon-glass"></i></a>
                                <a href="@Url.Action("Index", "Document",new { RegattaID = item.Id, DocumentType="list" })" class="btn btn-sm btn-default" alt="Documents"><i class="glyphicon glyphicon-wrench"></i></a>

                            </td>
                            <td>@item.RegattaYear</td>
                            <td>@item.StartDate.Value.ToString("dd MMM yyyy")</td>
                            <td>@item.Result</td>
                            <td class="pdsa-action-button-column"><a href="#" data-pdsa-action="delete" data-pdsa-val="@item.Id" class="btn btn-sm btn-default"><i class="glyphicon glyphicon-trash"></i></a></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    }
    <!-- End List Area-->
    <!--Detail Area-->

    if (Model.IsDetailVisible)
    {

        <div class="panel panel-primary">
            <div class="panel-heading">
                <h1 class="panel-title">
                    Regatta
                </h1>
            </div>
            <div class="panel-body">
                <!-- Begin Message Area -->
                <div class="row">
                    <div class="col-sm-12">
                        @if (!Model.IsValid)
                        {
                            <div class="alert alert-danger alert-dismissable" role="alert">
                                <button type="button" class="close" data-dissmiss="alert">
                                    <span aria-hidden="true">&times</span>

                                    <span class="sr-only">Close</span>
                                </button>
                                @Html.ValidationSummary(false)
                            </div>
                        }
                    </div>
                </div>
                <!-- End message Area-->
                <div class="form-group">
                    @Html.HiddenFor(m => m.Entity.Id)
                    @Html.LabelFor(m => m.Entity.RegattaName, "Regatta")
                    @Html.TextBoxFor(m => m.Entity.RegattaName, new { @class = "form-control" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.Entity.RegattaYear, "Year")
                    @Html.TextBoxFor(m => m.Entity.RegattaYear, new { @class = "form-control" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.Entity.StartDate, "Start Date")
                    @Html.Kendo().DatePickerFor(m => m.Entity.StartDate).Format("d/MM/yyyy").HtmlAttributes(new { @class = "form-control" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.Entity.Result, "Result")
                    @Html.TextBoxFor(m => m.Entity.Result, new { @class = "form-control" })
                </div>

            </div>
            <div class="panel-footer">
                <div class="row">
                    <div class="col-sm-12">
                        <button class="btn btn-primary" id="btnSave" data-pdsa-action="save">
                            <i class="glyphicon glyphicon-floppy-disk"></i>&nbsp; Save
                        </button>
                        <button class="btn btn-primary" formnovalidate id="btnCancel" data-pdsa-action="cancel">
                            <i class="glyphicon glyphicon-remove-circle"></i>&nbsp;Cancel
                        </button>
                    </div>
                </div>
            </div>
        </div>

    }

    <!-- End Detail Area-->

}

@section scripts
{


}

Views/Regatta/show.cshtml
@model DataRepository.Models.RegattaViewModel

@{
    ViewBag.Title = "Regattas";
}


      <!-- Start List Area  -->
   @if (Model.IsListAreaVisible)
    {
        <div class="table-responsive">
            <table class="table table-condensed table-bordered table-striped table-hover">
                <thead>
                    <tr>
                        <th>Regatta</th>
                        <th align="right">Action</th>
                        <th>Year</th>
                        <th>Date</th>
                        <th>Result</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.regattas)
                    {
                        <tr>
                            <td>
                                @Html.ActionLink(@item.RegattaName, "Display", "Regatta", new { RegattaID = item.Id, RegattaName = item.RegattaName }, null)
                               </td>
                            <td align="right">
                                <a href="@Url.Action("show", "Image",new { RegattaID = item.Id })" class="btn btn-sm btn-default" alt="Photos of this regatta"><i class="glyphicon glyphicon-camera"></i></a>
                                <a href="@Url.Action("show", "Document",new { RegattaID = item.Id, DocumentType="log" })" class="btn btn-sm btn-default" alt="Documents"><i class="glyphicon glyphicon-book"></i></a>
                              
                            </td>
                            <td>@item.RegattaYear</td>
                            <td>@item.StartDate.Value.ToString("dd MMM yyyy")</td>
                            <td>@item.Result</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    }
    <!-- End List Area-->

   